---
title: "Code_challenge"
author: "Ifedayo_ojo"
date: '2022-07-01'
output: html_document
---
## Question F
Loading the data into R environment 
```{r setup, include=FALSE}
# Load Library 
library(data.table)
# Load data to r worksheet
gene_df=fread("gene_disease_opt.csv")
# Check the data
head(gene_df, 4)
# Logically select the desired data 
selected=gene_df[score>0.4,.SD, by=.(gene_family)][order(score, gene_family, decreasing = T)]
# select the first 5 above the cut off for each gene_family.
new_selected=rbind(selected[gene_family=="OTHER"][1:5],selected[gene_family=="SLC"][1:5],selected[gene_family=="GPCR"][1:5])

#unique(selected$gene_family)
# View(new_selected)
# Write to  data to csv
fwrite(new_selected, file = "~/R_code/Code_challenge/Output/selected_associations.csv")


library(dplyr)
gene_family_summary=selected %>%
  group_by(gene_family) %>%
  summarise("No_Association"=n())

View(gene_family_summary)


```

```{r }
# Generate the plot using ggplot2
library(ggplot2)
ggplot(data = selected, aes(fill=gene_family, y=score, x="disease.name"))+
  geom_bar(stat = "identity", position="stack")+
  labs(title = "Stacked bar chart by association per gene")
  


```

## 




```{r question g}
# No of assocation after year 2020
cat("The number of assocation after 2020 is: ", selected[publicationYear>2020,.N])


# Get the assocaition after 2020 with missense variant'
missense_Var=selected[publicationYear>2020,][grepl("missense_variant",variantFunctionalConsequence.label)]

head(missense_Var,3)

cat("Total number of association with missense variant is : ", nrow(missense_Var))
```

### Question H
## The plot of the distribution of all assocaition 


```{r }

setwd("~/R_code/Code_challenge/graphics")
pdf("score_dst.pdf")
ggplot(selected, aes(x=selected$score), xlab="Score")+
   geom_density(alpha=.3)+
  theme_classic()+labs(title = "Distribution Curve for association Score")
dev.off()

setwd("~/R_code/Code_challenge")

  

```
###Question I

The function task 

```{r  }
# Create a function to return indexed matrix 
sortVariant=function(data){
  df=as.data.table(data)
  df2=df[,.(variantId, score)][order(variantId, decreasing = F)]
  sort_Variant=as.matrix(df2)
  return(sort_Variant)
}

# Try the fundtion with "selected" dataset
variant_mat=sortVariant(selected)
head(variant_mat,3)

```

Network Plot

```{r }
library(igraph)

y=data.frame(selected$disease.name[1:20],selected$score[1:20])

geneNet=graph.data.frame(y, directed = FALSE)


V(geneNet)
E(geneNet)
V(geneNet)$Label=V(geneNet)$name
V(geneNet)$degree=degree(geneNet)
set.seed(222)
setwd("~/R_code/Code_challenge/graphics")
pdf("gene_disease_ntw.pdf")
plot(geneNet,
     vertex.color=rainbow(52),
     edge.colour="red", layout=layout.kamada.kawai,
     vertex.label.cex=0.8, edge.arrow.size=0.1,
     vertex.size=V(geneNet)$degree*4)
title("Gene-disease Association network plot")
dev.off()




```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
